name: CD


on:
  push:
    branches: [ main, staging ]

  workflow_dispatch:

env: 
  APP_SECRETS: ${{ secrets.APP_SECRETS }}
  AWS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
  AWS_KEY_SECRET: ${{ secrets.AWS_KEY_SECRET }}
  STAGE: ${{ github.ref == 'refs/heads/main' && 'production' || 'staging' }}
  
jobs:
  deploy_aws:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: echo $STAGE
      - run: npm install -g serverless
      - run: serverless config credentials --provider aws --key $AWS_KEY_ID --secret $AWS_KEY_SECRET
      - run: echo $APP_SECRETS | base64 -di > secrets.yml
      - run: yarn
      - run: yarn run build-graphql --stage ${{env.STAGE}}
      - run: yarn deploy --stage ${{env.STAGE}} --verbose --conceal
